### PR TITLE
Bumped up cucumber to ^2.3.0

### PR DESCRIPTION
**Pull request by Marketionist**
**This pull request bumps up cucumber to ^2.3.0 and updates step definitions**

Also:
- updated all steps to use `defineSupportCode` (according to https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md)

Fixes https://github.com/Marketionist/protractor-cucumber-steps/issues/16

### CODE REVIEW

**Comment by Syslog2905** [comment]
// Now make sure that the new window is open in a new tab and we are navigating correctly to it
function switchToNewTabWindow() {
  var winHandles = browser.getAllWindowHandles();
  winHandles.then(function (handles) {
    var parentWindow = handles[0];
    var newTabWindow = handles[1];
    browser.switchTo().window(newTabWindow);
  })
};


var {defineSupportCode} = require('cucumber');
defineSupportCode(function ({Given, When, Then}) {

  //WHEN steps
  When('I go to URL {url}', function (url, callback) {
    browser.get(url);
    callback(null, 'sdfsdfsk');
  });

  When('I go to {page}.{elem}', function (page, elem, callback) {
    const url = pageObjects[page][elem];

    browser.get(url);
    callback();
  });

  When('I click {page}.{elem}', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);

    waitForDisplayed(elmnt);
    browser.wait(EC.elementToBeClickable(elmnt), customTimeout,
      `"${pageObjects[page][elem]}" ${errors.CLICKABLE}`);
    elmnt.click();
    callback();
  });

  When('I wait and click {page}.{elem}', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);
    const timeToWait = 300;

    waitForDisplayed(elmnt);
    browser.wait(EC.elementToBeClickable(elmnt), customTimeout,
      `"${pageObjects[page][elem]}" ${errors.CLICKABLE}`);
    setTimeout(function () {
      elmnt.click();
      callback();
    }, timeToWait);
  });

  When('I click {page}.{elem} if present', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);

    elmnt.isPresent().then(function (isPresent) {
      if (isPresent) {
        // Click only if element is present
        elmnt.click();

      }
      callback();
    });
  });

  When('I type {text} in the {page}.{elem}', function (text, page, elem, callback) {
    const inputField = composeLocator(page, elem);

    waitForDisplayed(inputField);
    browser.wait(EC.elementToBeClickable(inputField), customTimeout,
      `${pageObjects[page][elem]} ${errors.CLICKABLE}`);
    browser.actions().mouseMove(inputField).click().perform();
    inputField.sendKeys(text);
    callback();
  });

  When(/^I type "([^"]*)"."([^"]*)" in the "([^"]*)"."([^"]*)"$/, function (page1, element1, page2, element2, callback) {
    const inputField = composeLocator(page2, element2);

    waitForDisplayed(inputField);
    browser.wait(EC.elementToBeClickable(inputField), customTimeout,
      `${pageObjects[page2][element2]} ${errors.CLICKABLE}`);
    browser.actions().mouseMove(inputField).click().perform();
    inputField.sendKeys(pageObjects[page1][element1]);
    callback();
  });

  When('I wait for {d+} ms', {timeout: timeToWaitMax}, function (timeToWait, callback) {
    setTimeout(callback, timeToWait);
  });

  When('I wait for {page}.{elem} to be present', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);

    waitForDisplayed(elmnt);
    elmnt.isPresent().then(function (isPresent) {
      if (isPresent) {
        callback();
      } else {
        throw new Error(errors.PRESENT);
      }
    });
  });

  //THEN steps
  Then('{page}.{elem} should be present', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);
    //console.log(elmnt);

    expect(elmnt.isPresent()).to.eventually.equal(true).and.notify(callback);
  });

  Then('{page}.{elem} has text {text}', function (page, elem, text, callback) {
    const elmnt = composeLocator(page, elem);

    expect(elmnt.getText()).to.eventually.equal(text).and.notify(callback);
  });

  Then('the title should equal to {text}', function (text, callback) {
    expect(browser.getTitle()).to.eventually.equal(text).and.notify(callback);
  });

  Then('{page}.{elem} should not be present', function (page, elem, callback) {
    const elmnt = composeLocator(page, elem);

    expect(elmnt.isPresent()).to.eventually.equal(false).and.notify(callback);
  });

  // Take a callback as an additional argument to execute when the step is done
  Then('the file {fileName} is empty', function (fileName, callback) {
    fs.readFile(fileName, 'utf8', function (error, contents) {
      if (error) {
        callback(error);
      } else {
        expect(contents).to.eventually.equal('').and.notify(callback);
      }
    });
  });

  Then('{page1}.{element1} has text {page2}.{element2}', function (page1, element1, page2, element2, callback) {
    const elmnt = composeLocator(page1, element1);
    const text = pageObjects[page2][element2];

    expect(elmnt.getText()).to.eventually.equal(text).and.notify(callback);
  })
});

**Comment by Syslog2905** [comment]
Here are updated all old steps according to the new cucumber syntax and a function that handles going to a new tab in the browser.

**Comment by Marketionist** [comment]
@Syslog2905 are you sure that regular expressions in steps like:
```When(/^I type "([^"])"."([^"])" in the "([^"])"."([^"])"$/, ...```
should be changed to strings like:
```When('I type {page1}.{element1} in the {page2}.{element2}', ...```?

I still see the steps written with regular expressions in cucumber 2.3.0 changelog - https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#230-2017-06-01

**Comment by Syslog2905** [comment]
It works for me in other steps but you can try by yourself.

BR,
Syslog2904

**Comment by Marketionist** [comment]
Merging to master, @Syslog2905 thanks a lot for your contribution!

P.S. You can send a separate pull request with the function that handles going to a new tab in the browser - I'll be happy to review and accept it too.

**Pull request merged**
